Completed all tasks in Week 4 [Sys, Argparse, Decorators]
barklan/mipt_adv_py pull request #3
Opened 2020-09-28 15:10 UTC by barklan

[Start here (.ipynb main file)](https://github.com/barklan/mipt_adv_py/blob/w4/w4/w4.ipynb)

2020-09-29 13:17 UTC, alekseik1 requested changes
### Обязательные
1. Странное решение в Фиббоначчи:
```python
    try:
        n = int(sys.argv[1])
        print(fib(n))
    except:
        parser = createParser()
        namespace = parser.parse_args()
        print(fib(namespace.n))
```
Предполагалось, что это даст возможность передавать `n` как позиционный и через `-n`?
2. В программе 2 нету вывода ядра ОС.
3. В программе 4 нет вывода всех предыдущих простых чисел. Например, 1000-ое число было 7919. Тогда в `Logged primes:` должно было попасть 2, 5, 7 и т.п.
Насколько я понял, сейчас в `log.txt` пишутся только результаты предыдущих запусков.

### Необязательные
1. Круто, что ты сделал Фиббоначи через генераторы.
Более того, ты еще запоминаешь предыдущие результаты -- а это уже означает, что код будет быстрым. Класс!
2. В задании 7 в логгере много строк `log.writelines` и они разбросаны немного друг относительно друга. В больших проектах можно потерять след и перестать понимать структуру лога целиком. Поэтому можно заранее написать строку формата, а потом подставлять в нее аргументы последовательно. В твоем случае получилось бы что-то наподобие:
```python
LOGGER_FORMAT = '''\
Start time: {start_time}
Args: {args}
{return_value}
End time: {end_time}
Execution time: {exec_seconds} seconds
'''
```
а затем:
```python
LOGGER_FORMAT.format(
    start_time=start, 
    args=args,
    return_value=('-' if result else 'Return {}'.format(result)), 
    end_time=end_human,
    exec_seconds=round(exectime, 5)
)
```
Так структура логгера сразу была бы на виду целиком.

2020-09-29 14:35 UTC, barklan commented
Исправил. В Фиббоначи я понял это как задание - сделать так чтобы он вызывался как позиционный или как -n (то есть обязательно две возможности передачи), я не смог придумать как это сделать красивее.

2020-09-30 07:11 UTC, alekseik1 approved these changes
Теперь все ок

2020-09-30 07:11 UTC, alekseik1 commented on w4/task4.py
> +#  :\
И так сойдет :)

2020-09-30 07:11 UTC, alekseik1 commented on w4/w4.ipynb
> +      "2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251 257 2
Еще чуть-чуть -- и можно будет начать майнить биткоины

2020-09-30 08:22 UTC, merged