Week 5 Done (without arithmetic dragons)
barklan/mipt_adv_py pull request #4
Opened 2020-10-05 10:51 UTC by barklan

@alekseik1

2020-10-11 11:50 UTC, alekseik1 requested changes
Немного есть замечаний

2020-10-11 11:50 UTC, alekseik1 commented on w5/bad_solid.md
> +![Wasted](wasted.jpg)
Что? 😂

2020-10-11 11:50 UTC, alekseik1 commented on w5/basic_oop.md
> +- В объектно-ориентированном программировании **наследование** - это механизм базирования объекта или класса на другом объекте (наследование на основе прототипов) или классе (наследование на основе к
А что такое "дружественная функция" и как она реализуется в Питоне?

2020-10-11 11:50 UTC, alekseik1 commented on w5/t6.py
> +    def __init__(self, name, age, number_of_legs):
Наверно, стоило бы краткое описание зебры (про лучшую зебру и т.п.) засунуть в класс, иначе не получается полиморфизма

2020-10-11 13:21 UTC, barklan commented
Исправил

2020-10-11 13:38 UTC, barklan commented
Ошибка в драконах также исправлена

2020-10-12 07:41 UTC, alekseik1 approved these changes
Оперативно, однако. 20/20

2020-10-12 08:24 UTC, merged